apiVersion: v1
kind: Service
metadata:
  name: shell-runner-service
  namespace: shell-runner
  labels:
    app: shell-runner
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: shell-runner
