apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-runner-sa
  namespace: shell-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: shell-runner
  name: pod-manager
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: shell-runner
subjects:
  - kind: ServiceAccount
    name: shell-runner-sa
    namespace: shell-runner
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
